---
- name: converge

  hosts: all

  roles:

    - nephelaiio.plugins
    - nephelaiio.nfs

  pre_tasks:

    - name: update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      changed_when: false
