---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  playbooks:
    side_effect: side_effect.yml
scenario:
  name: default
  check_sequence:
    - destroy
    - cleanup
    - dependency
    - create
    - prepare
    - converge
verifier:
  name: ansible
