---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: centos/systemd:latest
    privileged: True
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: debian
    image: debian:stretch
    privileged: True
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: arch
    image: base/archlinux:latest
    privileged: True
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
