---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible
    pre_build_image: true
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  playbooks:
    side_effect: side_effect.yml
scenario:
  name: default
  check_sequence:
    - destroy
    - cleanup
    - dependency
    - create
    - prepare
    - converge
verifier:
  name: ansible
