---
- name: prepare

  hosts: all

  gather_facts: true

  become: true

  tasks:

    - name: installl nfs client on host
      ansible.builtin.package:
        name: nfs-common
      delegate_to: localhost

    - name: update apt package cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false
