---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  vars:
    mount_path: /mnt/backups
  tasks:
    - name: Create mount directory
      ansible.builtin.file:
        state: directory
        path: "{{ mount_path }}"

    - name: Mount nfs volume
      ansible.posix.mount:
        src: "{{ ansible_default_ipv4.address }}:/opt/backups"
        path: "{{ mount_path }}"
        opts: defaults,rw
        state: mounted
        fstype: nfs

    - name: Test nfs mount
      ansible.builtin.copy:
        dest: "{{ mount_path }}/test"
        content: molecule ci
