---
- name: verify

  hosts: localhost

  gather_facts: true

  tasks:

    - name: gather service facts
      ansible.builtin.service_facts:

    - block:

        - debug:
            var: services

      when: ansible_os_family == 'Debian'
