---
- name: verify

  hosts: localhost

  gather_facts: true

  become: true

  tasks:

    - name: mount nfs volume
      ansible.posix.mount:
        src: localhost:/nfs/ssd/shared_data
        path: /var/nfs/backups
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs

    - name: test nfs mount
      ansible.builtin.copy:
        dest: /var/nfs/backups/test
        content: molecule ci
