---
name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

defaults:
  run:
    working-directory: 'nephelaiio.nfs'

jobs:

  lint:

    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.nfs'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint ansible

      - name: Lint code.
        run: |
          set -e
          yamllint .
          ansible-lint .

  molecule:

    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu2004
          - ubuntu1804
          - ubuntu1604
          - debian10
          - centos7

    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.nfs'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install poetry
        run: pip3 install poetry

      - name: Install pips
        run: poetry install

      - name: Run Molecule tests.
        run: poetry run tox | tee ${{ matrix.image }}.ci.log
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image }}

      - name: Commit ci log
        run: |
          cd $GITHUB_WORKSPACE/nephelaiio.nfs
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.ci.log
          git commit -m "Add ci logs"

      - name: Push to master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: nephelaiio.nfs
          force: true
          branch: master
