---
name: Release
on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: 'nephelaiio.nfs'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.nfs'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-base

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
